### PR TITLE
Fix and optimize the PackSquash workflow

### PR DESCRIPTION
**Pull request by AlexTMjugador**
## Purpose
I was taking at look at [the public repositories that depend on the PackSquash GitHub action](https://github.com/ComunidadAylas/PackSquash-action/network/dependents?package_id=UGFja2FnZS0yOTYyMDA3OTkw) because, as one of its developers, I wanted to gauge how it is being used and how it may be improved. I'm always listening for feedback, but not everyone gives it, and sometimes it's better to see how a software is being used in the wild for oneself! :smile:

This repository is on that dependents list, and it looked interesting, so I read its PackSquash GitHub actions workflow. I noticed that it checked out the repository twice, which is not necessary to do, and it also installed Node, which is also not needed.

In addition, the PackSquash action sometimes failed the "Restoring cached data" step non-critically due to the branch name not being resolved correctly (i.e., being `heads/master` instead of `master`). An example of run that has this failure is https://github.com/osfanmuffin/muffinhunt-datapack/runs/5665866422. I'm not sure what causes the branch name to be wrong, though. I've committed a change in the action to the command used to get the branch name, and made a failure in this step output a warning, which may help pinning this down further. A failure restoring the cached data means that PackSquash won't get to reuse the ZIP file generated in the previous run, which is not great, but it works anyway, just slower. Let me know if you'd be interested in debugging this issue further!

## Approach
I've just removed the unnecessary steps in the workflow, as described. The PackSquash action failure to download the previous ZIP sometimes was interesting for me, and might be interesting for you too, but right now I don't think it's actionable by this repository in any form.

## Future work
None.

#### Checklist
- [ ] Included tests
- [ ] Updated documentation in [README](https://github.com/osfanbuff63/muffinhunt-datapack/blob/master/README.md) and/or [docs folder](/docs)
- [ ] Tested in the latest version of Minecraft

### CODE REVIEW

**Review by osfanbuff63 — APPROVED** [review]
Just fine with me! I'm not too experienced with GitHub Actions, and the PackSquash project was just what I needed :).

The original reason for setting up Node.JS is that for whatever reason it was a very outdated version (and was saying something regarding that) on the machine running it. As for the extra lines, I really don't know why those were there :P

**Comment by AlexTMjugador** [comment]
Thank you for merging!

As expected, even though the workflow now runs ~30 s faster, the previous ZIP download step still fails due to the branch name having an unexpected prefix:

Branch name resolution failure

I'm still not sure on the cause of that failure. I tried to reproduce it on a double checkout scenario, but the the action worked fine even with the changes I've made to try to address that reverted. Anyhow, it might be interesting for this workflow to bump the action version to `master`, instead of `v2`, at these lines, to make it use those changes:

https://github.com/osfanmuffin/muffinhunt-datapack/blob/0ae63a7651ca0c8cdabbca56d6285e6504d18a34/.github/workflows/packsquash.yml#L12-L14

By (temporarily) bumping the PackSquash action to this version you'll be able to clearly see what workflow runs are affected (a warning is now shown in this case), and we'll be able to check ASAP if any changes I push fix this.

Are you interested in doing this? :smile:

**Comment by osfanbuff63** [comment]
I'm good with that!

**Comment by osfanbuff63** [comment]
Done in `[8cbdf10](https://github.com/osfanmuffin/muffinhunt-datapack/commit/8cbdf10d998b9e3a7f9f646ea8efb3d5ee07bc99)'

**Comment by osfanbuff63** [comment]
Done!

**Comment by AlexTMjugador** [comment]
Great! It looks like it behaves fine now, but I'll keep an eye on future runs, just in case. Thank you for your help :heart:

**Comment by AlexTMjugador** [comment]
I observed that the changes I made on my part had an effect.

When a branch name cannot be retrieved because the repository is in a detached head state, which consistently happens on PR synchronize event runs, now an empty one is used, falling back to using the latest PackSquash artifact ever. Previously it would take as a branch name a git ref that is not a branch. This is not a behavior I intended, but it works for your repository now.

The rationale behind filtering artifacts that get reused by branch is that each branch may use different options in their workflows, and reusing the latest artifact without filtering by branch may result in unexpected results: the branch itself would no longer determine how the ZIP is generated.

I'll think what balances performance with expected behavior the most when considering PRs. I'd like to not entirely exclude them from the reuse feature, which is the trivial solution.

**Comment by osfanbuff63** [comment]
Thanks a lot! :D

**Pull request merged**
